[build-system]
build-backend = 'mesonpy'
requires = ['meson-python>=0.15']

[project]
name = 'vapoursynth-vcm'
dynamic = ['version']
description = 'vcm plugin for VapourSynth (API 4): pixel modifying, pixel moving, frequency domain and test pattern filters by V.C.Mohan'
readme = 'README.md'
requires-python = '>=3.8'
license = { file = 'LICENSE' }
dependencies = ['VapourSynth']

[tool.meson-python.args]
setup = ['-Dpython_package=true']

[tool.meson-python.wheel]
exclude = ['*/*.dll.a', '*/*.lib']
